# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: cfe32b36c045dcd064a25b74baf05e1a64fc2935fe35c881d536a35cdb257bef7c79ac3961e46ca463395ca60aa15d1477b898a955271662c7485b14f6c6c0fa

test:
  secret_key_base: 4b721b66908a8818112c1fa54a2b883af72541a21d0d12aa2ff3156b5ea1f6623300375f63bb61469c4721a7ba7e5899afb74201305b9636df893281495924c9

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
